# Generated by Django 5.1.6 on 2025-02-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('destination', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('guests', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
